name: Github CI/CD test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello $GITHUB_ACTOR!"
  
  test-job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the firs job"
  
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [ test-job1]
    steps: 
    - run: echo "ini adalah job deploy"
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ test-job1]
    steps:
    - run: echo "ini adalah deploy dev"
